//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepScaler) DeepCopyInto(out *StepScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepScaler.
func (in *StepScaler) DeepCopy() *StepScaler {
	if in == nil {
		return nil
	}
	out := new(StepScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StepScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepScalerList) DeepCopyInto(out *StepScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StepScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepScalerList.
func (in *StepScalerList) DeepCopy() *StepScalerList {
	if in == nil {
		return nil
	}
	out := new(StepScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StepScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepScalerSpec) DeepCopyInto(out *StepScalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	out.MinCPU = in.MinCPU.DeepCopy()
	out.MaxCPU = in.MaxCPU.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepScalerSpec.
func (in *StepScalerSpec) DeepCopy() *StepScalerSpec {
	if in == nil {
		return nil
	}
	out := new(StepScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepScalerStatus) DeepCopyInto(out *StepScalerStatus) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = new(int64)
		**out = **in
	}
	if in.StepsUpdatedAt != nil {
		in, out := &in.StepsUpdatedAt, &out.StepsUpdatedAt
		*out = (*in).DeepCopy()
	}
	if in.CurrentCPU != nil {
		in, out := &in.CurrentCPU, &out.CurrentCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepScalerStatus.
func (in *StepScalerStatus) DeepCopy() *StepScalerStatus {
	if in == nil {
		return nil
	}
	out := new(StepScalerStatus)
	in.DeepCopyInto(out)
	return out
}
